movieproject/authentication/urls.py
from . import views
from django.urls import path
app_name='authentication'

urlpatterns = [
path('reg',views.reg,name='reg'),
path('login',views.login,name='login'),
path('logout',views.logout,name='logout'),


]

movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [
    
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/<int:id>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),
    path('add_product/', views.add_product, name='add_product'),
    path('/edit_product/<int:id>/', views.edit_product, name='edit_product'),
    path('/delete_product/<int:id>/', views.delete_product, name='delete_product'),
    path('product/<int:product_id>/add_comment/', views.add_comment, name='add_comment'),
    path('product/<int:product_id>/add_rating/', views.add_rating, name='add_rating'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),

    
]

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls' ,  namespace='movieapp')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
    path('',include('search_app.urls', namespace='search_app')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns=[
    path('SearchResult',views.SearchResult,name='SearchResult'),

]

movieproject/movieapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.contrib.auth.models import AbstractUser




class User(models.Model):
    username=models.CharField(max_length=255)
    first_name=models.CharField(max_length=255)
    last_name=models.CharField(max_length=255)
    email=models.EmailField(unique=True)
    password=models.CharField(max_length=255)
    def __str__(self):
        return '{}'.format(self.username)
    
    
class category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('movieapp:products_by_category', args=[self.slug, self.id])

    def __str__(self):
        return '{}'.format(self.name)
    
class products(models.Model):
    name=models.CharField(max_length=250)
    slug=models.SlugField(max_length=250,unique=True)
    poster=models.ImageField(upload_to='poster1')
    description=models.TextField()
    release_date=models.DateField()
    actors=models.CharField(max_length=255)
    category_id=models.ForeignKey(category,on_delete=models.CASCADE)
    trailer_link=models.URLField()
    user=models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    
    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'


    def __str__(self):
        return '{}'.format(self.name)
    
    def get_url(self):
        return reverse('movieapp:prodCatdetail',args=[self.category_id.slug,self.slug])
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        if not isinstance(self.user, get_user_model()):
            # Fetch the user instance based on the provided user information
            self.user = get_user_model().objects.get(username=self.user.username)

        super().save(*args, **kwargs)
        
    
    
    def average_rating(self):
        ratings = Rating.objects.filter(product=self)
        if ratings.exists():
            return sum(rating.rating for rating in ratings) / ratings.count()
        return 0

    def total_ratings(self):
        return Rating.objects.filter(product=self).count()

class Comment(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product = models.ForeignKey(products, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Rating(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product = models.ForeignKey(products, on_delete=models.CASCADE)
    rating = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    def _str_(self):
        return f"{self.user.username} - {self.product.name} - {self.rating}"

    
    
    

movieproject/templates/add_comment.html
{% extends 'base.html' %}

{% block content %}
    <h2 style="padding-top:80px;">Add Comment</h2>
    <form method="post" action="{% url 'movieapp:add_comment' product_id=product.id %}">
    {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
        <a href="{% url 'movieapp:allProdCat' %}">Cancel</a>
    </form>
{% endblock %}

movieproject/templates/add_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Movie</title>
</head>
<body>
    <h2 style="padding-top:80px;">Add Movie</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Movie</button>
        <a href="{% url 'movieapp:allProdCat' %}"></a>
    </form>
</body>
</html>

movieproject/templates/add_rating.html
 {% extends 'base.html' %}
{% block content %}
  <h2 style="padding-top:80px;">Add Rating</h2>
  <form method="post" action="{% url 'movieapp:add_rating' product_id=product.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit Rating</button>

  </form>

{% endblock %} 
    {% comment %} <button type="button" onclick="window.location.href='{% url 'movieapp:allProdCat' %}'">Back to all Movies</button> {% endcomment %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/fc51e437b8.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">

  <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div>
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

movieproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
      {{ category.description|truncatewords:155 }}
   {% else %}
       welcome to...
   {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} -  
    {% else %}
         see  new collections - 
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
      <div>
        <div class="row my_row_class">
            <div class="mx-auto">
            <p class="text-center custom_a" ><a href="{% url 'movieapp:allProdCat' %}" class="custom_a" style="color:black;"></a> </p>
        </div>
            </div>
      </div>
   
      <div class="mx_auto" style="padding-bottom:50px;">
    
            <div class="my_image1" width="90%" height="50px" src="{{category.image.url}}" alt="{{category.name}}">
      </div>
      <br>
      <div>
             <h1 class="text-center my_title"><b>{{category.name}}</b></h1>
             <p class="text-center">{{category.description}}</p>
      </div>
    {% else %}
      <br>
      <div class="image-container">
         <h1 class="text-center my_title" style="font-weight: bold; padding-top:60px;">Hoopla Movie World </h1>
         <p class="text-center">"Hoopla Movie World: Where every frame tells a story, and every moment brings cinematic magic to life."</p>
      </div>
    {% endif %}
     <div class="containers">
      <div class="row mx_auto" style="padding-bottom:100px; padding-top:100px;">
        {% for product in products %}
           {% comment %} <div style="my_bottom_margin col-10 col-sm-6 col-md-4 col-lg-3"> {% endcomment %}
            <div class="my_bottom_margin col-9 col-sm-4 col-md-4 xol-lg-4">
              <div class="card text-center"  style="min-width:18rem; border-radius: 5px; box-shadow: 0 0 15px lightblue; margin-bottom:20px;">
            {% if product.poster %}
    <a href="{{ product.get_url }}">
        {% comment %} <img class="card-img-top my_image" src="{{ product.poster.url }}" alt="{{ product.name }}"> {% endcomment %}
        <img class="card-img-top" src="{{ product.poster.url }}" alt="{{ product.name }}" style="width:70%; height:500px; object-fit: cover;" >

    </a>
{% else %}
    <p>y</p>
{% endif %}
           <div class="card-body" style=" padding-bottom:10px">
             <h4>{{product.name}}</h4>
             <p>{{product.category_id}}</p>
           </div>
           </div>
           </div>
           {% endfor %} 
        {% endblock %}  

movieproject/templates/delete_product.html
{% extends 'base.html' %}
{% block content %}
  <div style="max-width: 400px; margin: 0 auto; padding: 20px; background-color: #f9f9f9; border-radius: 5px;">
    <h2 style="padding-top:80px;">Confirm Delete</h2>
    <p>Are you sure you want to delete the product '{{ product.name }}'? This action cannot be undone.</p>

    <form method="post" style="margin-top: 20px;">
      {% csrf_token %}
      <button type="submit" style="background-color: #ff6347; color: #fff; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">Yes, Delete</button>
      <a href="{% url 'movieapp:allProdCat' %}" style="margin-left: 10px; color: #333; text-decoration: none;">Cancel</a>
    </form>
  </div>
{% endblock %}

movieproject/templates/edit_product.html
 {% extends 'base.html' %}

{% block content %}
  <h2 style="padding-top:80px;">Edit Product</h2>
  <form method="post" enctype="multipart/form-data" style="padding-bottom: 100px;">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
    <a href="{% url 'movieapp:allProdCat' %}">Cancel</a>
  </form>
{% endblock %} 

movieproject/templates/edit_profile.html
{% extends 'base.html' %}
{% block content %}
<h2 style="padding-top:80px;">Edit Profile</h2>
<form method="post" action="{% url 'movieapp:edit_profile'  %}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="button" onclick="window.location.href='{% url 'movieapp:allProdCat' %}'">save Changes</button>
  <button type="submit">Save</button>
</form>
{% endblock %}

movieproject/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Page Title</title>
    <!-- Link to Bootstrap Icons CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
    <!-- Other CSS files or stylesheets -->
</head>
<body>
    <!-- Your HTML content here -->
    <div class="footer" style="background-color:rgb(117, 149, 85);">
        <p class="text-center">
            Copyright © 2024 Plex <br>
             Language: English (US)<br>
             <a href="https://twitter.com/example"><i class="bi bi-twitter"></i></a>
             <a href="https://www.facebook.com/example"><i class="bi bi-facebook"></i></a>
             <a href="https://www.instagram.com/example"><i class="bi bi-instagram"></i></a>
             
    </div>
    <!-- Other HTML content -->
</body>
</html>

movieproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Login</title>
</head>
<body style="font-family: Arial, sans-serif; background-color: #f5f5f5;">

<div style="max-width: 400px; margin: 0 auto; padding: 20px; background-color: #fff; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); margin-top: 100px;">
  <form action="{% url 'authentication:login' %}" method="post">
    {% csrf_token %}
    <label for="username" style="display: block; margin-bottom: 5px;">Username:</label>
    <input type="text" name="username" required style="width: 100%; padding: 10px; margin-bottom: 15px; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box;">

    <label for="password" style="display: block; margin-bottom: 5px;">Password:</label>
    <input type="password" name="password" required style="width: 100%; padding: 10px; margin-bottom: 15px; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box;">

    <input type="submit" value="Login" style="width: 100%; padding: 10px; background-color: #007bff; border: none; color: #fff; border-radius: 5px; cursor: pointer;">
  </form>
</div>

</body>
</html>

movieproject/templates/navbar.html
 <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top" style="background-color:rgb(117, 149, 85);">
    <div class="container-fluid">
      <a class="navbar-brand" href="#" style="color: white;">HM Movie</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item" style="margin-top: 7px;">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>

          <li class="nav-item dropdown {% if 'movieapp' in request.path %} active {% endif %}">
            <a class="nav-link dropdown-toggle" style="margin-top: 7px;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Movie
            </a>
            <ul class="dropdown-menu" style="background-color: lightgrey;">
              <li><a class="dropdown-item" href="{% url 'movieapp:allProdCat' %}">All Movies</a></li>
              <li><hr class="dropdown-divider"></li>
                {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
            {% if user.is_authenticated %}
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'movieapp:add_product' %}">Add Movie</a></li>
                    {% endif %}
            </ul>
          </li>

        <div class="ac" style="margin-left:860px; margin-top:0px;">
        <li class="nav-item dropdown {% if 'movieapp' in request.path %} active {% endif %}">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
        <ul class="dropdown-menu" style="background-color: lightgrey;">
        
                
          {% if user.is_authenticated %}
                    <span class="dropdown-item">Hello {{ user.username }} </span>
                    <li><hr class="dropdown-divider"></li>

                    {% if user.is_authenticated %}   
                     <li><a class="dropdown-item" href="{% url 'movieapp:edit_profile'%}">Edit Profile</a></li>
                {% endif %}
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'authentication:logout' %}">Logout</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'authentication:reg' %}">Register</a></li>
            <li><a class="dropdown-item" href="{% url 'authentication:login' %}">Login</a></li>
            {% endif %}
          </ul>
          </li>
          {% if user.is_authenticated %}
          {% endif %}
        </div>
        <li class="navv">
          {% if user.is_authenticated %}
            {% comment %} <a class="nav-link" href="#"><i class="fa-regular fa-user" style="font-size: x-large; margin-top: 5px;"></i></a> {% endcomment %}
            {% comment %}
            {% endcomment %}
            {% endif %}
          </li>
          </ul>
          <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get" style="padding: 5px; border-radius: 10px;">
            {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search" style="background-color: white; color: black;" autocomplete="off">
            <button class="btn" type="submit" style="background-color: None"><i class="fa-solid fa-magnifying-glass" style="color: black;"></i></button>
        </form>
      </div>
    </div>
  </nav>

movieproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
      {{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }} -  
    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class" style="padding-bottom: 50px;">
  <div class="mx-auto">
    <p style="margin-left:100px;"><a href="{% url 'movieapp:allProdCat' %}" style="text-decoration:none;color:lightblue;">Home</a> | <a href="{{product.category.get_url}}" style="style=width:10px; height:10px;">{{product.category}}</a> | {{product.name}}</p>
  </div>
    <div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div class="photo">
            <img src="{{product.poster.url}}" alt="{{product.name}}" style="width: 400px; height: 500px; margin-bottom:100px; border-radius: 10px; box-shadow: 0 0 10px black;">

        </div>
    </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6"  style="padding-bottom:100px;" >
            <div style="margin-right:100px;">
         <h1 class="my_prod_title">{{product.name}}</h1>
            <p>{{product.category_id}}</p>
                <p class="text-justify my_rod_text">{{product.description}}</p>
                {% if user == product.user %}
                <a href="{{ product.trailer_link }}" class="btn btn-primary">Watch Trailer</a><br><br>
           
    
                <a class="btn btn-success" href="{% url 'movieapp:edit_product' id=product.id %}">Edit</a>
                <a class="btn btn-danger" href="{% url 'movieapp:delete_product' id=product.id %}">delete</a>
                {% endif %} 
                {% if user.is_authenticated %} <br><br>
                <button type="button" class="btn btn-secondary" onclick="window.location.href='{% url 'movieapp:add_comment' product_id=product.id %}'">Add Comment</button>
                {% endif %}
                <br>
                <h3></h3>
                 {% for comment in product.comment_set.all %}
                <p>{{ comment.text }} - {{ comment.user.username }} at {{ comment.created_at }}</p>
                {% endfor %}
                 {% if user.is_authenticated %}  
                <button type="button" class="btn btn-secondary" onclick="window.location.href='{% url 'movieapp:add_rating' product_id=product.id %}'">Add Rating</button>
                <h2></h2>
                <p>Average Rating: {{ product.average_rating }}</p>
                <p>Total Ratings: {{ product.total_ratings }}</p>
               
               
                {% endif %}   
           </div>
    </div>
</div>
        {% endblock %}
    </div>
</div> 

movieproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Register</title>
</head>
<body style="font-family: Arial, sans-serif; background-color: #f5f5f5; padding: 20px;">

{% if messages %}
<div class="messages" style="margin-bottom: 20px;">
  {% for message in messages %}
  <div class="{{ message.tags }}" style="padding: 10px; background-color: #f8d7da; color: #721c24; border-radius: 5px; margin-bottom: 5px;">
    {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}

<div style="max-width: 400px; margin: 0 auto; background-color: #fff; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); padding: 20px;">
  <form action="{% url 'authentication:reg' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter your Username" style="width: 100%; padding: 10px; margin-bottom: 10px; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box;">
    <input type="text" name="first_name" placeholder="Enter your First Name" style="width: 100%; padding: 10px; margin-bottom: 10px; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box;">
    <input type="text" name="last_name" placeholder="Enter your Last Name" style="width: 100%; padding: 10px; margin-bottom: 10px; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box;">
    <input type="email" name="email" placeholder="Enter your Email" style="width: 100%; padding: 10px; margin-bottom: 10px; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box;">
    <input type="password" name="password" placeholder="Enter your Password" style="width: 100%; padding: 10px; margin-bottom: 10px; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box;">
    <input type="password" name="password1" placeholder="Confirm your Password" style="width: 100%; padding: 10px; margin-bottom: 10px; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box;">
    <input type="submit" value="Register" style="width: 100%; padding: 10px; background-color: #007bff; border: none; color: #fff; border-radius: 5px; cursor: pointer;">
  </form>
</div>

</body>
</html>

movieproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

     we have variety of products.
{% endblock %}
{% block title %}
  search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text" style="color:#DE3163">You have searched for:<b>"{{query}}"</b></p>
</div>
<div class="row mx_auto">
        {% for products in product %}
           <div class="my_bottom_margin col-9 col-sm-4 col-md-4 xol-lg-4">
           <div class="card text-center"  style="width:300px;height:350px; box-shadow: 0 0 10px rgba(222, 49, 99, 0.5);">
             <a href="{{products.get_url}}"><img class="card-img-top my_image" src="{{products.poster.url}}" style="width:300px;height:350px;filter: brightness(70%);" alt="{{products.name}}"></a>
           <div class="card-body">

           </div>
           </div>
           </div>

{% empty %}
<div class="row mx-auto">
    <p class="text-center my_search_text"> 0 results found</p>
</div>
{% endfor %}
</div>
{% endblock %}